In [1]:
import asyncio
import math
import pandas as pd

from itertools import chain, repeat

In [2]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [ ]:
from ib_insync import *
from ibkr.Class_IBKR_IB import IBKR_IB
ibkr = IBKR_IB(port=7496)

async def start_ibkr():
    await ibkr.connect()
    print("IBKR connected:", ibkr.ib.isConnected())

await start_ibkr()

IBKR connected: True

Error 200, reqId 27: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=1.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 28: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=1.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 29: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=2.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 31: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=3.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 30: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=2.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 33: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=4.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 32: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=3.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 34: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=4.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 35: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=5.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 36: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=5.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 37: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=6.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 38: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=6.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 39: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=7.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 40: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=7.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 41: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=8.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 42: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=8.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 43: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=9.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 44: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=9.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 45: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=10.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 46: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=10.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 47: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=11.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 48: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=11.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 49: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=12.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 50: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=12.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 51: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=13.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 52: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=13.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 53: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=14.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 56: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=15.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 54: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=14.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 55: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=15.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 57: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=16.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 58: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=16.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 59: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=17.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 60: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=17.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 61: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=18.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 62: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=18.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 151: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=45.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 152: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=45.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 155: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=46.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 156: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=46.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 159: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=47.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 163: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=48.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 160: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=47.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 164: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=48.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 167: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=49.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 168: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=49.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 171: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=50.5, right='C', exchange='SMART', currency='USD')
Error 200, reqId 172: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=50.5, right='P', exchange='SMART', currency='USD')
Error 200, reqId 193: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=61.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 194: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=61.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 195: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=62.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 196: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=62.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 197: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=63.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 198: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=63.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 199: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=64.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 201: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=65.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 200: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=64.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 202: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=65.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 203: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=66.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 204: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=66.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 205: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=67.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 206: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=67.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 207: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=68.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 208: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=68.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 209: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=69.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 210: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=69.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 211: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=70.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 212: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=70.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 213: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=71.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 214: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=71.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 215: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=72.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 216: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=72.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 217: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=73.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 218: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=73.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 219: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=74.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 220: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=74.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 221: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=75.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 222: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=75.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 223: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=76.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 224: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=76.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 225: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=77.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 226: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=77.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 227: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=78.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 229: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=79.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 228: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=78.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 230: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=79.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 231: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=80.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 232: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=80.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 233: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=81.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 235: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=82.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 236: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=82.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 237: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=83.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 239: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=84.0, right='C', exchange='SMART', currency='USD')
Error 200, reqId 234: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=81.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 238: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=83.0, right='P', exchange='SMART', currency='USD')
Error 200, reqId 241: No security definition has been found for the request, contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=85.0, right='C', exchange='SMART', currency='USD')

In [4]:
async def make_chains_from_symbols(symbols_list, product_type):

    contracts     = []
    details       = []
    option_chains = []

    for symbol in symbols_list:

        if product_type == 'equity':
            contract = Stock(symbol=symbol, exchange='SMART', currency="USD")
            fut_exch = ""
        elif product_type == "future":
            contract = Future(localSymbol=symbol, exchange='CME', currency="USD")
            fut_exch = "CME"

        contract = await ibkr.ib.qualifyContractsAsync(contract) # this may lead to a printed line since its return has nowhere to be mapped
        contracts.append(contract[0])

        print(contract[0])

        detail = await ibkr.ib.reqContractDetailsAsync(contract[0])
        details.append(detail[0])

        print(detail[0])

        option_chain = await ibkr.ib.reqSecDefOptParamsAsync(underlyingSymbol=detail[0].contract.symbol,
                                                             futFopExchange=fut_exch,
                                                             underlyingSecType=detail[0].contract.secType,
                                                             underlyingConId=detail[0].contract.conId
                                                            )
        option_chains.append(option_chain)

        print(option_chain[0])

        # print('count=', len(stocl_option_chain[0].expirations), stock_option_chain[0].expirations)
        # print('count=', len(stock_option_chain[0].strikes), stock_option_chain[0].strikes)
        # print("2 *", len(stock_option_chain[0].expirations), "*", len(stock_option_chain[0].strikes), "=", 
        #                       len(stock_option_chain[0].expirations) * len(stock_option_chain[0].strikes) * 2)

        # print('\n')

    return option_chains, details, contracts

In [5]:
stock_symbols = ['IBIT']

s_chain, s_detail, s_contracts = await make_chains_from_symbols(stock_symbols, 'equity')


future_symbols = [
                  'BTCM6',
                  'BTCN6',
                  'BTCQ6',
                  'BTCU6',
                  'BTCV6',
                  'BTCX6',
                  'BTCZ6'
                  ]


f_chain, f_detail, f_contracts = await make_chains_from_symbols(future_symbols, 'future')

combined_zip = chain(zip(s_chain, s_detail, repeat("equity")), zip(f_chain, f_detail, repeat("future")))

Stock(conId=677037673, symbol='IBIT', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='IBIT', tradingClass='NMS')
ContractDetails(contract=Contract(secType='STK', conId=677037673, symbol='IBIT', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='IBIT', tradingClass='NMS'), marketName='NMS', minTick=0.01, orderTypes='ACTIVETIM,AD,ADDONT,ADJUST,ALERT,ALGO,ALLOC,AON,AVGCOST,BASKET,BENCHPX,CASHQTY,COND,CONDORDER,DARKONLY,DARKPOLL,DAY,DEACT,DEACTDIS,DEACTEOD,DIS,DUR,GAT,GTC,GTD,GTT,HID,IBKRATS,ICE,IMB,IOC,LIT,LMT,LOC,MIDPX,MIT,MKT,MOC,MTL,NGCOMB,NODARK,NONALGO,OCA,OPG,OPGREROUT,PEGBENCH,PEGMID,POSTATS,POSTONLY,PREOPGRTH,PRICECHK,REL,REL2MID,RELPCTOFS,RPI,RTH,SCALE,SCALEODD,SCALERST,SIZECHK,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,SWEEP,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='SMART,AMEX,NYSE,CBOE,PHLX,ISE,CHX,ARCA,ISLAND,DRCTEDGE,BEX,BATS,EDGEA,BYX,IEX,EDGX,FOXRIVER,PEARL,NYSENAT,LTSE,MEMX,IBEOS,OVERNIGHT,TPLUS0,PSX,T24X', priceMagnifier=1, underConId=0, longName='ISHARES BITCOIN TRUST ETF', contractMonth='', industry='', category='', subcategory='', timeZoneId='US/Eastern', tradingHours='20260620:CLOSED;20260621:CLOSED;20260622:0400-20260622:2000;20260623:0400-20260623:2000;20260624:0400-20260624:2000;20260625:0400-20260625:2000', liquidHours='20260620:CLOSED;20260621:CLOSED;20260622:0930-20260622:1600;20260623:0930-20260623:1600;20260624:0930-20260624:1600;20260625:0930-20260625:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=1, underSymbol='', underSecType='', marketRuleIds='26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26', secIdList=[TagValue(tag='ISIN', value='US46438F1012')], realExpirationDate='', lastTradeTime='', stockType='ETF', minSize=0.0001, sizeIncrement=0.0001, suggestedSizeIncrement=100.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')
OptionChain(exchange='BATS', underlyingConId='677037673', tradingClass='IBIT', multiplier='100', expirations=['20260622', '20260624', '20260626', '20260629', '20260630', '20260701', '20260702', '20260706', '20260710', '20260717', '20260724', '20260731', '20260821', '20260831', '20260918', '20261016', '20261120', '20261130', '20261218', '20270115', '20270219', '20270319', '20270617', '20271217', '20280121', '20280616', '20281215'], strikes=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 28.5, 29.0, 29.5, 30.0, 30.5, 31.0, 31.5, 32.0, 32.5, 33.0, 33.5, 34.0, 34.5, 35.0, 35.5, 36.0, 36.5, 37.0, 37.5, 38.0, 38.5, 39.0, 39.5, 40.0, 40.5, 41.0, 41.5, 42.0, 42.5, 43.0, 43.5, 44.0, 44.5, 45.0, 45.5, 46.0, 46.5, 47.0, 47.5, 48.0, 48.5, 49.0, 49.5, 50.0, 50.5, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 105.0, 110.0, 115.0, 120.0, 125.0, 130.0, 135.0, 140.0])
Future(conId=751356962, symbol='BRR', lastTradeDateOrContractMonth='20260626', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6', tradingClass='BTC')
ContractDetails(contract=Contract(secType='FUT', conId=751356962, symbol='BRR', lastTradeDateOrContractMonth='20260626', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCM6', tradingClass='BTC'), marketName='BTC', minTick=5.0, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,BENCHPX,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,ICE,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,STPPROT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=296180912, longName='CME CF Bitcoin Reference Rate', contractMonth='202606', industry='', category='', subcategory='', timeZoneId='US/Central', tradingHours='20260620:CLOSED;20260618:1602-20260619:1600;20260619:1602-20260620:0200;20260620:0400-20260622:1600;20260622:1602-20260623:1600;20260623:1602-20260624:1600;20260624:1602-20260625:1600;20260625:1602-20260626:1000', liquidHours='20260620:CLOSED;20260621:CLOSED;20260622:0830-20260622:1515;20260623:0830-20260623:1515;20260624:0830-20260624:1515;20260625:0830-20260625:1515;20260625:1602-20260626:1000', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=2147483647, underSymbol='BRR', underSecType='IND', marketRuleIds='380', secIdList=[], realExpirationDate='20260626', lastTradeTime='11:00:00', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')
OptionChain(exchange='CME', underlyingConId='751356962', tradingClass='BTC', multiplier='5', expirations=['20260626'], strikes=[1000.0, 5000.0, 10000.0, 17500.0, 20000.0, 22500.0, 25000.0, 27500.0, 30000.0, 32500.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0, 48500.0, 49000.0, 49500.0, 50000.0, 50500.0, 51000.0, 51500.0, 52000.0, 52500.0, 53000.0, 53500.0, 54000.0, 54500.0, 55000.0, 55500.0, 56000.0, 56500.0, 57000.0, 57500.0, 58000.0, 58500.0, 59000.0, 59500.0, 60000.0, 60250.0, 60500.0, 60750.0, 61000.0, 61250.0, 61500.0, 61750.0, 62000.0, 62250.0, 62500.0, 62750.0, 63000.0, 63250.0, 63500.0, 63750.0, 64000.0, 64250.0, 64500.0, 64750.0, 65000.0, 65250.0, 65500.0, 65750.0, 66000.0, 66250.0, 66500.0, 66750.0, 67000.0, 67250.0, 67500.0, 67750.0, 68000.0, 68250.0, 68500.0, 68750.0, 69000.0, 69250.0, 69500.0, 69750.0, 70000.0, 70250.0, 70500.0, 70750.0, 71000.0, 71250.0, 71500.0, 71750.0, 72000.0, 72250.0, 72500.0, 73000.0, 73500.0, 74000.0, 74500.0, 75000.0, 75500.0, 76000.0, 76500.0, 77000.0, 77500.0, 78000.0, 78500.0, 79000.0, 79500.0, 80000.0, 80500.0, 81000.0, 81500.0, 82000.0, 82500.0, 83000.0, 83500.0, 84000.0, 84500.0, 85000.0, 85500.0, 86000.0, 86500.0, 87000.0, 87500.0, 88000.0, 88500.0, 89000.0, 89500.0, 90000.0, 90500.0, 91000.0, 91500.0, 92000.0, 92500.0, 93000.0, 93500.0, 94000.0, 94500.0, 95000.0, 95500.0, 96000.0, 96500.0, 97000.0, 97500.0, 98000.0, 98500.0, 99000.0, 99500.0, 100000.0, 100500.0, 101000.0, 101500.0, 102000.0, 102500.0, 103000.0, 103500.0, 104000.0, 104500.0, 105000.0, 105250.0, 105500.0, 105750.0, 106000.0, 106250.0, 106500.0, 106750.0, 107000.0, 107250.0, 107500.0, 107750.0, 108000.0, 108250.0, 108500.0, 108750.0, 109000.0, 109250.0, 109500.0, 109750.0, 110000.0, 110250.0, 110500.0, 110750.0, 111000.0, 111250.0, 111500.0, 111750.0, 112000.0, 112250.0, 112500.0, 112750.0, 113000.0, 113250.0, 113500.0, 113750.0, 114000.0, 114250.0, 114500.0, 114750.0, 115000.0, 115250.0, 115500.0, 115750.0, 116000.0, 116250.0, 116500.0, 116750.0, 117000.0, 117250.0, 117500.0, 117750.0, 118000.0, 118250.0, 118500.0, 118750.0, 119000.0, 119250.0, 119500.0, 119750.0, 120000.0, 120250.0, 120500.0, 120750.0, 121000.0, 121250.0, 121500.0, 121750.0, 122000.0, 122250.0, 122500.0, 122750.0, 123000.0, 123250.0, 123500.0, 123750.0, 124000.0, 124250.0, 124500.0, 124750.0, 125000.0, 126000.0, 127000.0, 127500.0, 128000.0, 129000.0, 130000.0, 131000.0, 132000.0, 132500.0, 133000.0, 134000.0, 135000.0, 136000.0, 137000.0, 137500.0, 138000.0, 139000.0, 140000.0, 141000.0, 142000.0, 142500.0, 143000.0, 144000.0, 145000.0, 146000.0, 147000.0, 147500.0, 148000.0, 149000.0, 150000.0, 152500.0, 155000.0, 157500.0, 160000.0, 162500.0, 165000.0, 167500.0, 170000.0, 172500.0, 175000.0, 177500.0, 180000.0, 182500.0, 185000.0, 187500.0, 190000.0, 192500.0, 195000.0, 197500.0, 200000.0, 202500.0, 205000.0, 207500.0, 210000.0, 212500.0, 215000.0, 217500.0, 220000.0, 222500.0, 225000.0, 230000.0, 235000.0, 240000.0, 245000.0, 250000.0, 255000.0, 260000.0, 265000.0, 270000.0, 275000.0, 280000.0, 285000.0, 290000.0, 295000.0, 300000.0, 305000.0, 310000.0, 315000.0, 320000.0, 325000.0, 330000.0, 335000.0, 340000.0, 345000.0, 350000.0, 355000.0, 360000.0, 365000.0, 370000.0, 375000.0, 380000.0, 385000.0, 390000.0, 400000.0, 450000.0, 500000.0, 550000.0, 600000.0])
Future(conId=850790355, symbol='BRR', lastTradeDateOrContractMonth='20260731', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCN6', tradingClass='BTC')
ContractDetails(contract=Contract(secType='FUT', conId=850790355, symbol='BRR', lastTradeDateOrContractMonth='20260731', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCN6', tradingClass='BTC'), marketName='BTC', minTick=5.0, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,BENCHPX,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,ICE,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,STPPROT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=296180912, longName='CME CF Bitcoin Reference Rate', contractMonth='202607', industry='', category='', subcategory='', timeZoneId='US/Central', tradingHours='20260620:CLOSED;20260618:1602-20260619:1600;20260619:1602-20260620:0200;20260620:0400-20260622:1600;20260622:1602-20260623:1600;20260623:1602-20260624:1600;20260624:1602-20260625:1600;20260625:1602-20260626:1600', liquidHours='20260620:CLOSED;20260621:CLOSED;20260622:0830-20260622:1515;20260623:0830-20260623:1515;20260624:0830-20260624:1515;20260625:0830-20260625:1515;20260625:1602-20260626:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=2147483647, underSymbol='BRR', underSecType='IND', marketRuleIds='380', secIdList=[], realExpirationDate='20260731', lastTradeTime='11:00:00', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')
OptionChain(exchange='CME', underlyingConId='850790355', tradingClass='BTC', multiplier='5', expirations=['20260731'], strikes=[10000.0, 17500.0, 20000.0, 22500.0, 25000.0, 27500.0, 30000.0, 32500.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0, 49000.0, 49500.0, 50000.0, 50500.0, 51000.0, 51500.0, 52000.0, 52500.0, 53000.0, 53500.0, 54000.0, 54500.0, 55000.0, 55250.0, 55500.0, 55750.0, 56000.0, 56250.0, 56500.0, 56750.0, 57000.0, 57250.0, 57500.0, 57750.0, 58000.0, 58250.0, 58500.0, 58750.0, 59000.0, 59250.0, 59500.0, 59750.0, 60000.0, 60250.0, 60500.0, 60750.0, 61000.0, 61250.0, 61500.0, 61750.0, 62000.0, 62250.0, 62500.0, 62750.0, 63000.0, 63250.0, 63500.0, 63750.0, 64000.0, 64250.0, 64500.0, 64750.0, 65000.0, 65250.0, 65500.0, 65750.0, 66000.0, 66250.0, 66500.0, 66750.0, 67000.0, 67250.0, 67500.0, 67750.0, 68000.0, 68250.0, 68500.0, 68750.0, 69000.0, 69250.0, 69500.0, 69750.0, 70000.0, 70250.0, 70500.0, 70750.0, 71000.0, 71250.0, 71500.0, 71750.0, 72000.0, 72250.0, 72500.0, 72750.0, 73000.0, 73250.0, 73500.0, 73750.0, 74000.0, 74250.0, 74500.0, 74750.0, 75000.0, 75250.0, 75500.0, 75750.0, 76000.0, 76250.0, 76500.0, 76750.0, 77000.0, 77250.0, 77500.0, 77750.0, 77800.0, 78000.0, 78250.0, 78500.0, 78750.0, 79000.0, 79250.0, 79500.0, 79750.0, 80000.0, 80250.0, 80500.0, 80750.0, 81000.0, 81250.0, 81500.0, 81750.0, 82000.0, 82250.0, 82500.0, 82750.0, 83000.0, 83250.0, 83500.0, 83750.0, 84000.0, 84250.0, 84500.0, 84750.0, 85000.0, 85250.0, 85500.0, 85750.0, 86000.0, 86250.0, 86500.0, 86750.0, 87000.0, 87250.0, 87500.0, 87750.0, 88000.0, 88250.0, 88500.0, 88750.0, 89000.0, 89250.0, 89500.0, 89750.0, 90000.0, 90250.0, 90500.0, 90750.0, 91000.0, 91250.0, 91500.0, 91750.0, 92000.0, 92250.0, 92500.0, 92750.0, 93000.0, 93250.0, 93500.0, 93750.0, 94000.0, 94250.0, 94500.0, 94750.0, 95000.0, 95250.0, 95500.0, 95750.0, 96000.0, 96250.0, 96500.0, 96750.0, 97000.0, 97250.0, 97500.0, 97750.0, 98000.0, 98250.0, 98500.0, 98750.0, 99000.0, 99250.0, 99500.0, 99750.0, 100000.0, 100500.0, 101000.0, 101500.0, 102000.0, 102500.0, 103000.0, 103500.0, 104000.0, 104500.0, 105000.0, 105500.0, 106000.0, 106500.0, 107000.0, 107500.0, 108000.0, 108500.0, 109000.0, 109500.0, 110000.0, 110500.0, 111000.0, 111500.0, 112000.0, 112500.0, 113000.0, 114000.0, 115000.0, 116000.0, 117000.0, 117500.0, 118000.0, 119000.0, 120000.0, 121000.0, 122000.0, 122500.0, 123000.0, 124000.0, 125000.0, 126000.0, 127000.0, 127500.0, 128000.0, 129000.0, 130000.0, 132500.0, 135000.0, 137500.0, 140000.0, 142500.0, 145000.0, 147500.0, 150000.0, 152500.0, 155000.0, 157500.0, 160000.0, 162500.0, 165000.0, 167500.0, 170000.0, 172500.0, 175000.0, 177500.0, 180000.0, 182500.0, 185000.0, 187500.0, 190000.0, 192500.0, 195000.0, 197500.0, 200000.0, 202500.0, 205000.0, 207500.0, 210000.0, 212500.0, 215000.0, 217500.0, 220000.0, 222500.0, 225000.0, 230000.0, 235000.0, 240000.0, 245000.0, 250000.0, 255000.0])
Future(conId=859040542, symbol='BRR', lastTradeDateOrContractMonth='20260828', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCQ6', tradingClass='BTC')
ContractDetails(contract=Contract(secType='FUT', conId=859040542, symbol='BRR', lastTradeDateOrContractMonth='20260828', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCQ6', tradingClass='BTC'), marketName='BTC', minTick=5.0, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,BENCHPX,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,ICE,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,STPPROT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=296180912, longName='CME CF Bitcoin Reference Rate', contractMonth='202608', industry='', category='', subcategory='', timeZoneId='US/Central', tradingHours='20260620:CLOSED;20260618:1602-20260619:1600;20260619:1602-20260620:0200;20260620:0400-20260622:1600;20260622:1602-20260623:1600;20260623:1602-20260624:1600;20260624:1602-20260625:1600;20260625:1602-20260626:1600', liquidHours='20260620:CLOSED;20260621:CLOSED;20260622:0830-20260622:1515;20260623:0830-20260623:1515;20260624:0830-20260624:1515;20260625:0830-20260625:1515;20260625:1602-20260626:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=2147483647, underSymbol='BRR', underSecType='IND', marketRuleIds='380', secIdList=[], realExpirationDate='20260828', lastTradeTime='11:00:00', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')
OptionChain(exchange='CME', underlyingConId='859040542', tradingClass='BTC', multiplier='5', expirations=['20260828'], strikes=[10000.0, 17500.0, 20000.0, 22500.0, 25000.0, 27500.0, 30000.0, 32500.0, 35000.0, 37500.0, 40000.0, 42500.0, 45000.0, 47500.0, 49000.0, 49500.0, 50000.0, 50500.0, 51000.0, 51500.0, 52000.0, 52500.0, 53000.0, 53500.0, 54000.0, 54500.0, 55000.0, 55500.0, 56000.0, 56500.0, 57000.0, 57500.0, 58000.0, 58500.0, 59000.0, 59500.0, 60000.0, 60500.0, 61000.0, 61500.0, 62000.0, 62500.0, 62750.0, 63000.0, 63250.0, 63500.0, 63750.0, 64000.0, 64250.0, 64500.0, 64750.0, 65000.0, 65250.0, 65500.0, 65750.0, 66000.0, 66250.0, 66500.0, 66750.0, 67000.0, 67250.0, 67500.0, 67750.0, 68000.0, 68250.0, 68500.0, 68750.0, 69000.0, 69250.0, 69500.0, 69750.0, 70000.0, 70250.0, 70500.0, 70750.0, 71000.0, 71250.0, 71500.0, 71750.0, 72000.0, 72250.0, 72500.0, 72750.0, 73000.0, 73250.0, 73500.0, 73750.0, 74000.0, 74250.0, 74500.0, 74750.0, 75000.0, 75250.0, 75500.0, 75750.0, 76000.0, 76250.0, 76500.0, 76750.0, 77000.0, 77250.0, 77500.0, 77750.0, 78000.0, 78250.0, 78500.0, 78750.0, 79000.0, 79250.0, 79500.0, 79750.0, 80000.0, 80250.0, 80500.0, 80750.0, 81000.0, 81250.0, 81500.0, 81750.0, 82000.0, 82250.0, 82500.0, 82750.0, 83000.0, 83250.0, 83500.0, 83750.0, 84000.0, 84250.0, 84500.0, 84750.0, 85000.0, 85250.0, 85500.0, 85750.0, 86000.0, 86250.0, 86500.0, 86750.0, 87000.0, 87250.0, 87500.0, 87750.0, 88000.0, 88250.0, 88500.0, 88750.0, 89000.0, 89250.0, 89500.0, 89750.0, 90000.0, 90250.0, 90500.0, 90750.0, 91000.0, 91250.0, 91500.0, 91750.0, 92000.0, 92250.0, 92500.0, 92750.0, 93000.0, 93500.0, 94000.0, 94500.0, 95000.0, 95500.0, 96000.0, 96500.0, 97000.0, 97500.0, 98000.0, 98500.0, 99000.0, 99500.0, 100000.0, 100500.0, 101000.0, 101500.0, 102000.0, 102500.0, 103000.0, 103500.0, 104000.0, 104500.0, 105000.0, 105500.0, 106000.0, 106500.0, 107000.0, 107500.0, 108000.0, 108500.0, 109000.0, 109500.0, 110000.0, 110500.0, 111000.0, 111500.0, 112000.0, 112500.0, 113000.0, 114000.0, 115000.0, 116000.0, 117000.0, 117500.0, 118000.0, 119000.0, 120000.0, 121000.0, 122000.0, 122500.0, 123000.0, 124000.0, 125000.0, 127500.0, 130000.0, 132500.0, 135000.0, 137500.0, 140000.0, 142500.0, 145000.0, 147500.0, 150000.0, 152500.0, 155000.0, 157500.0, 160000.0, 162500.0, 165000.0, 167500.0, 170000.0, 172500.0, 175000.0, 177500.0, 180000.0, 182500.0, 185000.0, 187500.0, 190000.0, 192500.0, 195000.0, 197500.0, 200000.0, 202500.0, 205000.0, 207500.0, 210000.0, 212500.0, 215000.0, 217500.0, 220000.0, 222500.0, 225000.0, 230000.0, 235000.0, 240000.0, 245000.0, 250000.0, 255000.0])
Future(conId=772435574, symbol='BRR', lastTradeDateOrContractMonth='20260925', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCU6', tradingClass='BTC')
ContractDetails(contract=Contract(secType='FUT', conId=772435574, symbol='BRR', lastTradeDateOrContractMonth='20260925', multiplier='5', exchange='CME', currency='USD', localSymbol='BTCU6', tradingClass='BTC'), marketName='BTC', minTick=5.0, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,BENCHPX,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,ICE,IOC,LIT,LMT,LTH,MIT,MKT,MKTPROT,MTL,NGCOMB,NONALGO,OCA,PEGBENCH,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,STPPROT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=296180912, longName='CME CF Bitcoin Reference Rate', contractMonth='202609', industry='', category='', subcategory='', timeZoneId='US/Central', tradingHours='20260620:CLOSED;20260618:1602-20260619:1600;20260619:1602-20260620:0200;20260620:0400-20260622:1600;20260622:1602-20260623:1600;20260623:1602-20260624:1600;20260624:1602-20260625:1600;20260625:1602-20260626:1600', liquidHours='20260620:CLOSED;20260621:CLOSED;20260622:0830-20260622:1515;20260623:0830-20260623:1515;20260624:0830-20260624:1515;20260625:0830-20260625:1515;20260625:1602-20260626:1600', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=2147483647, underSymbol='BRR', underSecType='IND', marketRuleIds='380', secIdList=[], realExpirationDate='20260925', lastTradeTime='11:00:00', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')

In [6]:
option_contracts = []

for chain, details, product_type in combined_zip:
    for expiry in chain[0].expirations:
        for strike in chain[0].strikes:
            for right in ['C', 'P']:
                
                if product_type == 'equity':
                    option_contract = Option(lastTradeDateOrContractMonth=expiry,
                                                    strike=float(strike),
                                                    right=right,
                                                    symbol=details.contract.symbol,
                                                    exchange=details.contract.exchange,
                                                    currency=details.contract.currency,
                                                    )
                
                elif product_type == 'future':
                    option_contract = FuturesOption(lastTradeDateOrContractMonth=expiry,
                                                    strike=float(strike),
                                                    right=right,
                                                    symbol=details.contract.symbol,
                                                    exchange=details.contract.exchange,
                                                    currency=details.contract.currency,
                                                    )
                option_contracts.append(option_contract)

option_contracts = await ibkr.ib.qualifyContractsAsync(*option_contracts) # this may lead to printed lines since its return has nowhere to be mapped

# print(len(option_contracts))

Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=1.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=1.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=2.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=2.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=3.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=3.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=4.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=4.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=5.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=5.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=6.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=6.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=7.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=7.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=8.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=8.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=9.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=9.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=10.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=10.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=11.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=11.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=12.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=12.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=13.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=13.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=14.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=14.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=15.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=15.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=16.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=16.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=17.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=17.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=18.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=18.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=45.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=45.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=46.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=46.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=47.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=47.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=48.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=48.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=49.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=49.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=50.5, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=50.5, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=61.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=61.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=62.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=62.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=63.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=63.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=64.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=64.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=65.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=65.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=66.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=66.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=67.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=67.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=68.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=68.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=69.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=69.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=70.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=70.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=71.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=71.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=72.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=72.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=73.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=73.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=74.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=74.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=75.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=75.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=76.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=76.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=77.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=77.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=78.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=78.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=79.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=79.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=80.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=80.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=81.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=81.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=82.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=82.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=83.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=83.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=84.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=84.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=85.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=85.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=86.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=86.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=87.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=87.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=88.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=88.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=89.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=89.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=90.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=90.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=91.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=91.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=92.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=92.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=93.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=93.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=94.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=94.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=95.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=95.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=96.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=96.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=97.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=97.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=98.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=98.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=99.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=99.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=100.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=100.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=105.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=105.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=110.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=110.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=115.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=115.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=120.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=120.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=125.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=125.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=130.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=130.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=135.0, right='C', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=135.0, right='P', exchange='SMART', currency='USD')
Unknown contract: Option(symbol='IBIT', lastTradeDateOrContractMonth='20260622', strike=140.0, right='C', exchange='SMART', currency='USD')

In [7]:
def clean_num(x):
    """
    Convert IBKR nan / -1 / None style missing values to None.
    """
    if x is None:
        return None
    try:
        if math.isnan(x):
            return None
    except TypeError:
        pass
    if x == -1:
        return None
    return x

In [8]:
def ticker_row(ticker):
    contract = ticker.contract
    return {
            "conId": getattr(ticker.contract, "conId", None),
            "secType": getattr(contract, "secType", None),
            "symbol": getattr(contract, "symbol", None),
            "expiration": getattr(contract, "lastTradeDateOrContractMonth", None),
            "right": getattr(contract, "right", None),
            "strike": getattr(contract, "strike", None),

            "close": clean_num(getattr(ticker, "close", None)),
        #    "volume": clean_num(getattr(ticker, "volume", None)),
            "avgVolume": clean_num(getattr(ticker, "avVolume", None)),
            "futuresOpenInterest": clean_num(getattr(ticker, "futuresOpenInterest", None)),
            "putOpenInterest": clean_num(getattr(ticker, "putOpenInterest", None)),
            "callOpenInterest": clean_num(getattr(ticker, "callOpenInterest", None)),
        }

In [9]:
async def get_data(contracts, batch_size=50, wait_seconds=30):
    
    generic_ticks = "100,101,165,588"
    all_rows = []

    for i in range(0, len(contracts), batch_size):
        batch = contracts[i:i + batch_size]
        tickers = []

        print(f"Requesting {i} to {i + len(batch) - 1} of {len(contracts)}")

        for contract in batch:
            ticker = ibkr.ib.reqMktData(
                contract,
                genericTickList=generic_ticks,
                snapshot=False,
            )
            tickers.append(ticker)

        await asyncio.sleep(wait_seconds)

        rows = [ticker_row(ticker) for ticker in tickers]
        all_rows.extend(rows)

        # IMPORTANT: cancel streaming data before next batch
        for ticker in tickers:
            ibkr.ib.cancelMktData(ticker.contract)

        await asyncio.sleep(2)  # small pause between batches

    return pd.DataFrame(all_rows)

In [10]:
linear_contracts = [*f_contracts, *s_contracts] 
df_linear  = await get_data(linear_contracts, batch_size = 25, wait_seconds=60)
df_linear

Requesting 0 to 7 of 8

,conId,secType,symbol,expiration,right,strike,close,avgVolume,futuresOpenInterest,putOpenInterest,callOpenInterest
0,751356962,FUT,BRR,20260626,,0.0,62945.000000,NaN,0.0,0.0,0.0
1,850790355,FUT,BRR,20260731,,0.0,63240.000000,NaN,0.0,0.0,0.0
2,859040542,FUT,BRR,20260828,,0.0,63495.000000,NaN,0.0,0.0,0.0
3,772435574,FUT,BRR,20260925,,0.0,63745.000000,NaN,0.0,0.0,0.0
4,876880607,FUT,BRR,20261030,,0.0,64115.000000,NaN,0.0,0.0,0.0
5,887699043,FUT,BRR,20261127,,0.0,64425.000000,NaN,0.0,0.0,0.0
6,751356958,FUT,BRR,20261224,,0.0,64680.000000,NaN,0.0,0.0,0.0
7,677037673,STK,IBIT,,,0.0,36.360001,440638.0,NaN,0.0,0.0

In [11]:
df_options = await get_data(option_contracts, batch_size = 25, wait_seconds=60)
df_options

Requesting 0 to 24 of 6714
Requesting 25 to 49 of 6714
Requesting 50 to 74 of 6714
Requesting 75 to 99 of 6714
Requesting 100 to 124 of 6714
Requesting 125 to 149 of 6714
Requesting 150 to 174 of 6714
Requesting 175 to 199 of 6714
Requesting 200 to 224 of 6714
Requesting 225 to 249 of 6714
Requesting 250 to 274 of 6714
Requesting 275 to 299 of 6714
Requesting 300 to 324 of 6714
Requesting 325 to 349 of 6714
Requesting 350 to 374 of 6714
Requesting 375 to 399 of 6714
Requesting 400 to 424 of 6714
Requesting 425 to 449 of 6714
Requesting 450 to 474 of 6714
Requesting 475 to 499 of 6714
Requesting 500 to 524 of 6714
Requesting 525 to 549 of 6714
Requesting 550 to 574 of 6714
Requesting 575 to 599 of 6714
Requesting 600 to 624 of 6714
Requesting 625 to 649 of 6714
Requesting 650 to 674 of 6714
Requesting 675 to 699 of 6714
Requesting 700 to 724 of 6714
Requesting 725 to 749 of 6714
Requesting 750 to 774 of 6714
Requesting 775 to 799 of 6714
Requesting 800 to 824 of 6714
Requesting 825 to 849 of 6714
Requesting 850 to 874 of 6714
Requesting 875 to 899 of 6714
Requesting 900 to 924 of 6714
Requesting 925 to 949 of 6714
Requesting 950 to 974 of 6714
Requesting 975 to 999 of 6714
Requesting 1000 to 1024 of 6714
Requesting 1025 to 1049 of 6714
Requesting 1050 to 1074 of 6714
Requesting 1075 to 1099 of 6714
Requesting 1100 to 1124 of 6714
Requesting 1125 to 1149 of 6714
Requesting 1150 to 1174 of 6714
Requesting 1175 to 1199 of 6714
Requesting 1200 to 1224 of 6714
Requesting 1225 to 1249 of 6714
Requesting 1250 to 1274 of 6714
Requesting 1275 to 1299 of 6714
Requesting 1300 to 1324 of 6714
Requesting 1325 to 1349 of 6714
Requesting 1350 to 1374 of 6714
Requesting 1375 to 1399 of 6714
Requesting 1400 to 1424 of 6714
Requesting 1425 to 1449 of 6714
Requesting 1450 to 1474 of 6714
Requesting 1475 to 1499 of 6714
Requesting 1500 to 1524 of 6714
Requesting 1525 to 1549 of 6714
Requesting 1550 to 1574 of 6714
Requesting 1575 to 1599 of 6714
Requesting 1600 to 1624 of 6714
Requesting 1625 to 1649 of 6714
Requesting 1650 to 1674 of 6714
Requesting 1675 to 1699 of 6714
Requesting 1700 to 1724 of 6714
Requesting 1725 to 1749 of 6714
Requesting 1750 to 1774 of 6714
Requesting 1775 to 1799 of 6714
Requesting 1800 to 1824 of 6714
Requesting 1825 to 1849 of 6714
Requesting 1850 to 1874 of 6714
Requesting 1875 to 1899 of 6714
Requesting 1900 to 1924 of 6714
Requesting 1925 to 1949 of 6714
Requesting 1950 to 1974 of 6714
Requesting 1975 to 1999 of 6714
Requesting 2000 to 2024 of 6714
Requesting 2025 to 2049 of 6714
Requesting 2050 to 2074 of 6714
Requesting 2075 to 2099 of 6714
Requesting 2100 to 2124 of 6714
Requesting 2125 to 2149 of 6714
Requesting 2150 to 2174 of 6714
Requesting 2175 to 2199 of 6714
Requesting 2200 to 2224 of 6714
Requesting 2225 to 2249 of 6714
Requesting 2250 to 2274 of 6714
Requesting 2275 to 2299 of 6714
Requesting 2300 to 2324 of 6714
Requesting 2325 to 2349 of 6714
Requesting 2350 to 2374 of 6714
Requesting 2375 to 2399 of 6714
Requesting 2400 to 2424 of 6714
Requesting 2425 to 2449 of 6714
Requesting 2450 to 2474 of 6714
Requesting 2475 to 2499 of 6714
Requesting 2500 to 2524 of 6714
Requesting 2525 to 2549 of 6714
Requesting 2550 to 2574 of 6714
Requesting 2575 to 2599 of 6714
Requesting 2600 to 2624 of 6714
Requesting 2625 to 2649 of 6714
Requesting 2650 to 2674 of 6714
Requesting 2675 to 2699 of 6714
Requesting 2700 to 2724 of 6714
Requesting 2725 to 2749 of 6714
Requesting 2750 to 2774 of 6714
Requesting 2775 to 2799 of 6714
Requesting 2800 to 2824 of 6714
Requesting 2825 to 2849 of 6714
Requesting 2850 to 2874 of 6714
Requesting 2875 to 2899 of 6714
Requesting 2900 to 2924 of 6714
Requesting 2925 to 2949 of 6714
Requesting 2950 to 2974 of 6714
Requesting 2975 to 2999 of 6714
Requesting 3000 to 3024 of 6714
Requesting 3025 to 3049 of 6714
Requesting 3050 to 3074 of 6714
Requesting 3075 to 3099 of 6714
Requesting 3100 to 3124 of 6714
Requesting 3125 to 3149 of 6714
Requesting 3150 to 3174 of 6714
Requesting 3175 to 3199 of 6714
Requesting 3200 to 3224 of 6714
Requesting 3225 to 3249 of 6714
Requesting 3250 to 3274 of 6714
Requesting 3275 to 3299 of 6714
Requesting 3300 to 3324 of 6714
Requesting 3325 to 3349 of 6714
Requesting 3350 to 3374 of 6714
Requesting 3375 to 3399 of 6714
Requesting 3400 to 3424 of 6714
Requesting 3425 to 3449 of 6714
Requesting 3450 to 3474 of 6714
Requesting 3475 to 3499 of 6714
Requesting 3500 to 3524 of 6714
Requesting 3525 to 3549 of 6714
Requesting 3550 to 3574 of 6714
Requesting 3575 to 3599 of 6714
Requesting 3600 to 3624 of 6714
Requesting 3625 to 3649 of 6714
Requesting 3650 to 3674 of 6714
Requesting 3675 to 3699 of 6714
Requesting 3700 to 3724 of 6714
Requesting 3725 to 3749 of 6714
Requesting 3750 to 3774 of 6714
Requesting 3775 to 3799 of 6714
Requesting 3800 to 3824 of 6714
Requesting 3825 to 3849 of 6714
Requesting 3850 to 3874 of 6714
Requesting 3875 to 3899 of 6714
Requesting 3900 to 3924 of 6714
Requesting 3925 to 3949 of 6714
Requesting 3950 to 3974 of 6714
Requesting 3975 to 3999 of 6714
Requesting 4000 to 4024 of 6714
Requesting 4025 to 4049 of 6714
Requesting 4050 to 4074 of 6714
Requesting 4075 to 4099 of 6714
Requesting 4100 to 4124 of 6714
Requesting 4125 to 4149 of 6714
Requesting 4150 to 4174 of 6714
Requesting 4175 to 4199 of 6714
Requesting 4200 to 4224 of 6714
Requesting 4225 to 4249 of 6714
Requesting 4250 to 4274 of 6714
Requesting 4275 to 4299 of 6714
Requesting 4300 to 4324 of 6714
Requesting 4325 to 4349 of 6714
Requesting 4350 to 4374 of 6714
Requesting 4375 to 4399 of 6714
Requesting 4400 to 4424 of 6714
Requesting 4425 to 4449 of 6714
Requesting 4450 to 4474 of 6714
Requesting 4475 to 4499 of 6714
Requesting 4500 to 4524 of 6714
Requesting 4525 to 4549 of 6714
Requesting 4550 to 4574 of 6714
Requesting 4575 to 4599 of 6714
Requesting 4600 to 4624 of 6714
Requesting 4625 to 4649 of 6714
Requesting 4650 to 4674 of 6714
Requesting 4675 to 4699 of 6714
Requesting 4700 to 4724 of 6714
Requesting 4725 to 4749 of 6714
Requesting 4750 to 4774 of 6714
Requesting 4775 to 4799 of 6714
Requesting 4800 to 4824 of 6714
Requesting 4825 to 4849 of 6714
Requesting 4850 to 4874 of 6714
Requesting 4875 to 4899 of 6714
Requesting 4900 to 4924 of 6714
Requesting 4925 to 4949 of 6714
Requesting 4950 to 4974 of 6714
Requesting 4975 to 4999 of 6714
Requesting 5000 to 5024 of 6714
Requesting 5025 to 5049 of 6714
Requesting 5050 to 5074 of 6714
Requesting 5075 to 5099 of 6714
Requesting 5100 to 5124 of 6714
Requesting 5125 to 5149 of 6714
Requesting 5150 to 5174 of 6714
Requesting 5175 to 5199 of 6714
Requesting 5200 to 5224 of 6714
Requesting 5225 to 5249 of 6714
Requesting 5250 to 5274 of 6714
Requesting 5275 to 5299 of 6714
Requesting 5300 to 5324 of 6714
Requesting 5325 to 5349 of 6714
Requesting 5350 to 5374 of 6714
Requesting 5375 to 5399 of 6714
Requesting 5400 to 5424 of 6714
Requesting 5425 to 5449 of 6714
Requesting 5450 to 5474 of 6714
Requesting 5475 to 5499 of 6714
Requesting 5500 to 5524 of 6714
Requesting 5525 to 5549 of 6714
Requesting 5550 to 5574 of 6714
Requesting 5575 to 5599 of 6714
Requesting 5600 to 5624 of 6714
Requesting 5625 to 5649 of 6714
Requesting 5650 to 5674 of 6714
Requesting 5675 to 5699 of 6714
Requesting 5700 to 5724 of 6714
Requesting 5725 to 5749 of 6714
Requesting 5750 to 5774 of 6714
Requesting 5775 to 5799 of 6714
Requesting 5800 to 5824 of 6714
Requesting 5825 to 5849 of 6714
Requesting 5850 to 5874 of 6714
Requesting 5875 to 5899 of 6714
Requesting 5900 to 5924 of 6714
Requesting 5925 to 5949 of 6714
Requesting 5950 to 5974 of 6714
Requesting 5975 to 5999 of 6714
Requesting 6000 to 6024 of 6714
Requesting 6025 to 6049 of 6714
Requesting 6050 to 6074 of 6714
Requesting 6075 to 6099 of 6714
Requesting 6100 to 6124 of 6714
Requesting 6125 to 6149 of 6714
Requesting 6150 to 6174 of 6714
Requesting 6175 to 6199 of 6714
Requesting 6200 to 6224 of 6714
Requesting 6225 to 6249 of 6714
Requesting 6250 to 6274 of 6714
Requesting 6275 to 6299 of 6714
Requesting 6300 to 6324 of 6714
Requesting 6325 to 6349 of 6714
Requesting 6350 to 6374 of 6714
Requesting 6375 to 6399 of 6714
Requesting 6400 to 6424 of 6714
Requesting 6425 to 6449 of 6714
Requesting 6450 to 6474 of 6714
Requesting 6475 to 6499 of 6714
Requesting 6500 to 6524 of 6714
Requesting 6525 to 6549 of 6714
Requesting 6550 to 6574 of 6714
Requesting 6575 to 6599 of 6714
Requesting 6600 to 6624 of 6714
Requesting 6625 to 6649 of 6714
Requesting 6650 to 6674 of 6714
Requesting 6675 to 6699 of 6714
Requesting 6700 to 6713 of 6714

,conId,secType,symbol,expiration,right,strike,close,avgVolume,futuresOpenInterest,putOpenInterest,callOpenInterest
0,890245019,OPT,IBIT,20260622,C,19.0,17.39,None,None,0.0,0.0
1,890246741,OPT,IBIT,20260622,P,19.0,0.00,None,None,0.0,0.0
2,890245072,OPT,IBIT,20260622,C,20.0,16.39,None,None,0.0,0.0
3,890246786,OPT,IBIT,20260622,P,20.0,0.00,None,None,0.0,0.0
4,890245132,OPT,IBIT,20260622,C,21.0,15.39,None,None,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6709,756512288,FOP,BRR,20261224,P,500000.0,426905.00,None,None,0.0,0.0
6710,756512281,FOP,BRR,20261224,C,550000.0,5.00,None,None,0.0,0.0
6711,756512251,FOP,BRR,20261224,P,550000.0,475935.00,None,None,0.0,0.0
6712,756512303,FOP,BRR,20261224,C,600000.0,0.00,None,None,0.0,0.0
6713,756512278,FOP,BRR,20261224,P,600000.0,524970.00,None,None,0.0,0.0

In [12]:
df_option_conIds = (
    df_options.pivot_table(
        index=["symbol", "strike"],
        columns=["expiration", "right"],
        values="conId",
        aggfunc="first"
    )
    .sort_index()
    .sort_index(axis=1)
    .reset_index()
)

df_option_conIds

expiration symbol   strike 20260622     20260624         20260626  \
right                             C   P        C   P            C
0             BRR   1000.0      NaN NaN      NaN NaN  751506503.0
1             BRR   5000.0      NaN NaN      NaN NaN  751506548.0
2             BRR  10000.0      NaN NaN      NaN NaN  751506561.0
3             BRR  17500.0      NaN NaN      NaN NaN  852657225.0
4             BRR  20000.0      NaN NaN      NaN NaN  764688659.0
..            ...      ...      ...  ..      ...  ..          ...
527          IBIT    120.0      NaN NaN      NaN NaN          NaN
528          IBIT    125.0      NaN NaN      NaN NaN          NaN
529          IBIT    130.0      NaN NaN      NaN NaN          NaN
530          IBIT    135.0      NaN NaN      NaN NaN          NaN
531          IBIT    140.0      NaN NaN      NaN NaN          NaN

expiration              20260629      ...     20270617               \
right                 P        C   P  ...            C            P
0           751506545.0      NaN NaN  ...          NaN          NaN
1           751506518.0      NaN NaN  ...          NaN          NaN
2           751506558.0      NaN NaN  ...          NaN          NaN
3           852657015.0      NaN NaN  ...          NaN          NaN
4           764688665.0      NaN NaN  ...          NaN          NaN
..                  ...      ...  ..  ...          ...          ...
527                 NaN      NaN NaN  ...  812339736.0  812340411.0
528                 NaN      NaN NaN  ...  812339784.0  812340474.0
529                 NaN      NaN NaN  ...  820670481.0  820670611.0
530                 NaN      NaN NaN  ...  820670532.0  820670659.0
531                 NaN      NaN NaN  ...  820670569.0  820670702.0

expiration     20271217                  20280121              20280616      \
right                 C            P            C            P        C   P
0                   NaN          NaN          NaN          NaN      NaN NaN
1                   NaN          NaN          NaN          NaN      NaN NaN
2                   NaN          NaN          NaN          NaN      NaN NaN
3                   NaN          NaN          NaN          NaN      NaN NaN
4                   NaN          NaN          NaN          NaN      NaN NaN
..                  ...          ...          ...          ...      ...  ..
527         796581180.0  796581256.0  816970623.0  816970877.0      NaN NaN
528         799997845.0  799998059.0  816970678.0  816970947.0      NaN NaN
529         799997915.0  799998137.0  820670860.0  820670974.0      NaN NaN
530         799997984.0  799998214.0  820670896.0  820671018.0      NaN NaN
531         820670736.0  820670814.0  820670934.0  820671049.0      NaN NaN

expiration 20281215
right             C   P
0               NaN NaN
1               NaN NaN
2               NaN NaN
3               NaN NaN
4               NaN NaN
..              ...  ..
527             NaN NaN
528             NaN NaN
529             NaN NaN
530             NaN NaN
531             NaN NaN

[532 rows x 66 columns]

In [ ]:
df_option_prices = (
    df_options.pivot_table(
        index=["symbol", "strike"],
        columns=["expiration", "right"],
        values="close",
        aggfunc="first"
    )
    .sort_index()
    #.sort_index(axis=1)
    .reset_index()
)

df_option_prices

expiration symbol   strike 20260622     20260624     20260626      20260629  \
right                             C   P        C   P        C    P        C
0             BRR   1000.0      NaN NaN      NaN NaN  61895.0  0.0      NaN
1             BRR   5000.0      NaN NaN      NaN NaN  57900.0  0.0      NaN
2             BRR  10000.0      NaN NaN      NaN NaN  52905.0  0.0      NaN
3             BRR  17500.0      NaN NaN      NaN NaN  45410.0  0.0      NaN
4             BRR  20000.0      NaN NaN      NaN NaN  42910.0  0.0      NaN
..            ...      ...      ...  ..      ...  ..      ...  ...      ...
527          IBIT    120.0      NaN NaN      NaN NaN      NaN  NaN      NaN
528          IBIT    125.0      NaN NaN      NaN NaN      NaN  NaN      NaN
529          IBIT    130.0      NaN NaN      NaN NaN      NaN  NaN      NaN
530          IBIT    135.0      NaN NaN      NaN NaN      NaN  NaN      NaN
531          IBIT    140.0      NaN NaN      NaN NaN      NaN  NaN      NaN

expiration      ... 20270617         20271217         20280121          \
right        P  ...        C       P        C       P        C       P
0          NaN  ...      NaN     NaN      NaN     NaN      NaN     NaN
1          NaN  ...      NaN     NaN      NaN     NaN      NaN     NaN
2          NaN  ...      NaN     NaN      NaN     NaN      NaN     NaN
3          NaN  ...      NaN     NaN      NaN     NaN      NaN     NaN
4          NaN  ...      NaN     NaN      NaN     NaN      NaN     NaN
..          ..  ...      ...     ...      ...     ...      ...     ...
527        NaN  ...     0.30   83.64     0.73   83.64     0.83   83.64
528        NaN  ...     0.27   88.64     0.67   88.64     0.77   88.64
529        NaN  ...     0.25   93.64     0.62   93.64     0.70   93.64
530        NaN  ...     0.23   98.64     0.57   98.64     0.65   98.64
531        NaN  ...     0.22  103.64     0.55  103.64     0.61  103.64

expiration 20280616     20281215
right             C   P        C   P
0               NaN NaN      NaN NaN
1               NaN NaN      NaN NaN
2               NaN NaN      NaN NaN
3               NaN NaN      NaN NaN
4               NaN NaN      NaN NaN
..              ...  ..      ...  ..
527             NaN NaN      NaN NaN
528             NaN NaN      NaN NaN
529             NaN NaN      NaN NaN
530             NaN NaN      NaN NaN
531             NaN NaN      NaN NaN

[532 rows x 66 columns]

In [16]:
df_option_prices.to_csv("file.csv")

In [ ]:
df_option_prices.columns = pd.MultiIndex.from_tuples([
    ("strike", "K") if col == ("strike", "") or col == "strike"
    else (col, "") if not isinstance(col, tuple)
    else col
    for col in df_option_prices.columns
])

[stock_close] = df_linear.loc[df_linear['secType'] == 'STK', 'close'] 
df_option_prices.insert(
    loc=1,                 # between symbol and strike
    column=("stock", "S"),
    value=stock_close         # your constant
)

In [19]:
for expiration in df_option_prices.columns.get_level_values(0).unique():

    call_col = (expiration, "C")
    put_col  = (expiration, "P")

    cps_col = (expiration, "C-P-S")
    kcps_col = (expiration, "K-(C-P-S)")

    rate_col  = (expiration, "combo_return_rate")

    tv_col = (expiration, "time_value")


    if call_col in df_option_prices.columns and put_col in df_option_prices.columns:

        df_option_prices[cps_col] = (
            df_option_prices[call_col] - df_option_prices[put_col] - df_option_prices[("stock", "S")])

        df_option_prices[kcps_col] = (
            df_option_prices[("strike", "K")] + df_option_prices[cps_col])
    
        df_option_prices[rate_col] = (
            df_option_prices[kcps_col] / -df_option_prices[cps_col])

        df_option_prices[tv_col] = df_option_prices[[call_col, put_col]].min(axis=1)
    
df_option_prices.sort_index(axis=1)
df_option_prices

    symbol      stock   strike 20260622     20260624     20260626       \
                    S        K        C   P        C   P        C    P
0      BRR  36.360001   1000.0      NaN NaN      NaN NaN  61895.0  0.0
1      BRR  36.360001   5000.0      NaN NaN      NaN NaN  57900.0  0.0
2      BRR  36.360001  10000.0      NaN NaN      NaN NaN  52905.0  0.0
3      BRR  36.360001  17500.0      NaN NaN      NaN NaN  45410.0  0.0
4      BRR  36.360001  20000.0      NaN NaN      NaN NaN  42910.0  0.0
..     ...        ...      ...      ...  ..      ...  ..      ...  ...
527   IBIT  36.360001    120.0      NaN NaN      NaN NaN      NaN  NaN
528   IBIT  36.360001    125.0      NaN NaN      NaN NaN      NaN  NaN
529   IBIT  36.360001    130.0      NaN NaN      NaN NaN      NaN  NaN
530   IBIT  36.360001    135.0      NaN NaN      NaN NaN      NaN  NaN
531   IBIT  36.360001    140.0      NaN NaN      NaN NaN      NaN  NaN

    20260629  ...          20280121            20280616            \
           C  ... combo_return_rate time_value    C-P-S K-(C-P-S)
0        NaN  ...               NaN        NaN      NaN       NaN
1        NaN  ...               NaN        NaN      NaN       NaN
2        NaN  ...               NaN        NaN      NaN       NaN
3        NaN  ...               NaN        NaN      NaN       NaN
4        NaN  ...               NaN        NaN      NaN       NaN
..       ...  ...               ...        ...      ...       ...
527      NaN  ...          0.006965       0.83      NaN       NaN
528      NaN  ...          0.006198       0.77      NaN       NaN
529      NaN  ...          0.005414       0.70      NaN       NaN
530      NaN  ...          0.004838       0.65      NaN       NaN
531      NaN  ...          0.004376       0.61      NaN       NaN

                                 20281215                              \
    combo_return_rate time_value    C-P-S K-(C-P-S) combo_return_rate
0                 NaN        NaN      NaN       NaN               NaN
1                 NaN        NaN      NaN       NaN               NaN
2                 NaN        NaN      NaN       NaN               NaN
3                 NaN        NaN      NaN       NaN               NaN
4                 NaN        NaN      NaN       NaN               NaN
..                ...        ...      ...       ...               ...
527               NaN        NaN      NaN       NaN               NaN
528               NaN        NaN      NaN       NaN               NaN
529               NaN        NaN      NaN       NaN               NaN
530               NaN        NaN      NaN       NaN               NaN
531               NaN        NaN      NaN       NaN               NaN


    time_value
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
..         ...
527        NaN
528        NaN
529        NaN
530        NaN
531        NaN

[532 rows x 195 columns]

df_option_prices = df_option_prices.sort_index(axis=1)
df_option_prices.to_csv("file.csv")